# -----------------------------------------------------------------------------
# Fluent Bit ConfigMap
# -----------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: efklog
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     warn
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            docker
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db
        Read_from_Head    False

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        Keep_Log            Off
        DNS_Retries         2
        DNS_Wait_Time       1

  output-elasticsearch.conf: |
    [OUTPUT]
        Name              es
        Match             *
        Host              elasticsearch-logging-es-http.efklog.svc
        Port              9200
        Index             k8s-logs
        Type              _doc
        tls               On
        tls.verify        On
        tls.ca_file       /etc/elasticsearch/certs/ca.crt
        HTTP_User         elastic
        HTTP_Passwd       ${ELASTIC_PASSWORD}
        Logstash_Format   On
        Logstash_Prefix   k8s-logs
        Retry_Limit       False
        Suppress_Type_Name On
        

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep  On
